# Generated by Django 2.2 on 2019-04-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifier', models.CharField(choices=[('aff.', 'aff.'), ('cf.', 'cf.'), ('forsan', 'forsan'), ('near', 'near'), ('?', '?')], max_length=8, null=True)),
                ('date_accessioned', models.DateField()),
                ('date_received', models.DateField()),
                ('quantity_received', models.IntegerField()),
                ('recvd_type', models.CharField(choices=[('ALAY', 140047252139312), ('BBPL', 140047252099360), ('BRPL', 140047252139376), ('BUDC', 140047252139440), ('BUDD', 140047252134296), ('BULB', 140047252134408), ('CLUM', 140047252134520), ('CORM', 140047252134632), ('DIVI', 140047252139504), ('GRAF', 140047252134800), ('LAYE', 140047252134912), ('PLNT', 140047252139568), ('PSBU', 140047252139632), ('RCUT', 140047252139696), ('RHIZ', 140047252135192), ('ROOC', 140047252139760), ('ROOT', 140047252135304), ('SCIO', 140047252135416), ('SEDL', 140047252139824), ('SEED', 140047252135584), ('SPOR', 140047252135696), ('SPRL', 140047252139888), ('TUBE', 140047252135864), ('UNKN', 140047263802120), ('URCU', 140047252116800), ('BBIL', 140047252127960), ('VEGS', 140047252116872), ('SCKR', 140047252139952), (None, '')], max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
