# Generated by Django 2.2 on 2019-04-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20190421_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='recvd_type',
            field=models.CharField(choices=[('ALAY', 140508002942448), ('BBPL', 140508002902304), ('BRPL', 140508002942512), ('BUDC', 140508002942576), ('BUDD', 140508002556480), ('BULB', 140508002556592), ('CLUM', 140508002556704), ('CORM', 140508002556816), ('DIVI', 140508002942640), ('GRAF', 140508002556984), ('LAYE', 140508002557096), ('PLNT', 140508002942704), ('PSBU', 140508002942768), ('RCUT', 140508002942832), ('RHIZ', 140508002557376), ('ROOC', 140508002942896), ('ROOT', 140508002557488), ('SCIO', 140508002557600), ('SEDL', 140508002934832), ('SEED', 140508002557768), ('SPOR', 140508002557880), ('SPRL', 140508002934896), ('TUBE', 140508002943136), ('UNKN', 140508014609160), ('URCU', 140508002923840), ('BBIL', 140508002943360), ('VEGS', 140508002923912), ('SCKR', 140508002934960), (None, '')], max_length=4, null=True),
        ),
    ]
