# Generated by Django 2.2 on 2019-04-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20190421_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='date_accessioned',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='date_received',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='qualifier',
            field=models.CharField(blank=True, choices=[('aff.', 'aff.'), ('cf.', 'cf.'), ('forsan', 'forsan'), ('near', 'near'), ('?', '?'), (None, '')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='quantity_received',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='accession',
            name='recvd_type',
            field=models.CharField(blank=True, choices=[('ALAY', 140532320271600), ('BBPL', 140532320227616), ('BRPL', 140532320271664), ('BUDC', 140532320271728), ('BUDD', 140532320266648), ('BULB', 140532320266760), ('CLUM', 140532320266872), ('CORM', 140532320266984), ('DIVI', 140532320271792), ('GRAF', 140532320267152), ('LAYE', 140532320267264), ('PLNT', 140532320271856), ('PSBU', 140532320271920), ('RCUT', 140532320271984), ('RHIZ', 140532320267544), ('ROOC', 140532320272048), ('ROOT', 140532320267656), ('SCIO', 140532320267768), ('SEDL', 140532320272112), ('SEED', 140532320267936), ('SPOR', 140532320268048), ('SPRL', 140532320272176), ('TUBE', 140532320268216), ('UNKN', 140532331934472), ('URCU', 140532320249152), ('BBIL', 140532320260312), ('VEGS', 140532320249224), ('SCKR', 140532320272240), (None, '')], max_length=4, null=True),
        ),
    ]
