# Generated by Django 2.2 on 2019-04-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20190421_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='accessioned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='received_type',
            field=models.CharField(blank=True, choices=[('ALAY', 'Air layer'), ('BBPL', 'Balled & burlapped plant'), ('BRPL', 'Bare root plant'), ('BUDC', 'Bud cutting'), ('BUDD', 'Budded'), ('BULB', 'Bulb'), ('CLUM', 'Clump'), ('CORM', 'Corm'), ('DIVI', 'Division'), ('GRAF', 'Graft'), ('LAYE', 'Layer'), ('PLNT', 'Planting'), ('PSBU', 'Pseudobulb'), ('RCUT', 'Rooted cutting'), ('RHIZ', 'Rhizome'), ('ROOC', 'Root cutting'), ('ROOT', 'Root'), ('SCIO', 'Scion'), ('SEDL', 'Seedling'), ('SEED', 'Seed'), ('SPOR', 'Spore'), ('SPRL', 'Sporeling'), ('TUBE', 'Tuber'), ('UNKN', 'Unknown'), ('URCU', 'Unrooted cutting'), ('BBIL', 'Bulbil'), ('VEGS', 'Vegetative spreading'), ('SCKR', 'Root sucker'), (None, '')], max_length=4, null=True),
        ),
    ]
