# Generated by Django 2.2 on 2019-04-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_auto_20190422_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='code',
            field=models.CharField(default=2019.0001, max_length=12),
            preserve_default=False,
        ),
    ]
