# Generated by Django 2.2 on 2019-04-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_accession_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
