# Generated by Django 2.2 on 2019-04-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_auto_20190423_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='verification',
            unique_together={('accession', 'code')},
        ),
    ]
