# Generated by Django 2.2 on 2019-05-01 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_auto_20190424_1525'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='verification',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='verification',
            name='code',
        ),
    ]
