# Generated by Django 2.2 on 2019-07-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_auto_20190502_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='fullname',
        ),
    ]
