# Generated by Django 2.2.2 on 2019-07-10 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0015_contact_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('code', models.CharField(default='', max_length=12)),
                ('abbreviation', models.CharField(default='', max_length=12)),
                ('description', models.TextField(default='')),
                ('institution_address', models.CharField(default='', max_length=64)),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_for', to='collection.Contact')),
                ('technical_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_for', to='collection.Contact')),
            ],
        ),
    ]
