# Generated by Django 2.2.2 on 2019-07-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0017_auto_20190711_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessions', to='collection.Institution'),
        ),
    ]
