# Generated by Django 2.2.2 on 2019-07-11 13:52

from django.db import migrations


def depopulate(apps, schema_editor):
    Institution = apps.get_model('collection', 'institution')
    Institution.objects.all().delete()


def create_institution(apps, schema_editor):
    # We can't import the model directly as it may be a newer version than
    # this migration expects. We use the historical version.
    Institution = apps.get_model('collection', 'institution')
    Accession = apps.get_model('collection', 'accession')
    Institution.objects.all().delete()
    (institution, created)= Institution.objects.get_or_create(name='single institution')
    for a in Accession.objects.all():
        a.institution = institution
        a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0018_accession_collection'),
    ]

    operations = [
        migrations.RunPython(create_institution, depopulate),
    ]
