# Generated by Django 2.2.2 on 2019-07-11 15:21

import django.contrib.gis.db.models.fields
from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0019_single_institution'),
    ]

    operations = [
        CreateExtension('postgis'),
        migrations.AddField(
            model_name='institution',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]

