# Generated by Django 2.2.2 on 2019-07-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0020_institution_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='location',
            new_name='geometry',
        ),
    ]
