# Generated by Django 2.2.2 on 2019-07-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0021_auto_20190712_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='diameter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
