# Generated by Django 2.2 on 2019-04-20 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(choices=[(1, 'regnum'), (2, 'subregnum'), (3, 'divisio'), (4, 'subdivisio'), (5, 'classis'), (6, 'subclassis'), (7, 'ordo'), (8, 'subordo'), (9, 'familia'), (10, 'subfamilia'), (11, 'tribus'), (12, 'subtribus'), (13, 'genus'), (14, 'subgenus'), (15, 'sectio'), (16, 'subsectio'), (17, 'series'), (18, 'subseries'), (19, 'species'), (20, 'subspecies'), (21, 'varietas'), (22, 'subvarietas'), (23, 'forma'), (24, 'subforma')])),
                ('epithet', models.CharField(max_length=40)),
                ('authorship', models.CharField(max_length=120)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtaxa', to='taxonomy.Taxon')),
            ],
        ),
    ]
