# Generated by Django 2.2 on 2019-04-20 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='accepted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synonyms', to='taxonomy.Taxon'),
        ),
    ]
