# Generated by Django 2.2 on 2019-04-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_taxon_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
