# Generated by Django 2.2 on 2019-04-20 22:27

from django.db import migrations

def depopulate(apps, schema_editor):
    Taxon = apps.get_model('taxonomy', 'Taxon')
    Taxon.objects.all().delete()

def import_defaults(apps, schema_editor):
    # We can't import the model directly as it may be a newer version than
    # this migration expects. We use the historical version.
    Taxon = apps.get_model('taxonomy', 'Taxon')
    Taxon.objects.all().delete()

    import csv
    with open('taxonomy/migrations/0004_auto_20190420_2227.taxon.csv', newline='') as csvfile:
         spamreader = csv.reader(csvfile, delimiter=',', quotechar='"')
         header = next(spamreader)
         for row in spamreader:
             item = dict(zip(header, row))
             for key in header:
                 if item[key] == '':
                     del item[key]
             obj = Taxon.objects.create(**item)
             obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_taxon_year'),
    ]

    operations = [
        migrations.RunPython(import_defaults, depopulate),
    ]
