# Generated by Django 2.2 on 2019-04-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_auto_20190420_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxon',
            options={'verbose_name_plural': 'taxa'},
        ),
    ]
