# Generated by Django 2.2 on 2019-04-30 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0007_auto_20190421_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='accepted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synonyms', to='taxonomy.Taxon'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='authorship',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtaxa', to='taxonomy.Taxon'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
