# Generated by Django 2.2 on 2019-05-08 20:00

from django.db import migrations
from django.db.models import Max


def import_families(apps, schema_editor):
    # We can't import the model directly as it may be a newer version than
    # this migration expects. We use the historical version.
    Taxon = apps.get_model('taxonomy', 'Taxon')
    Rank = apps.get_model('taxonomy', 'Rank')
    import csv
    args = Taxon.objects.all()
    last_id = args.aggregate(Max('id'))['id__max']
    with open('taxonomy/migrations/0010_auto_20190508_2000.taxon.csv', newline='') as csvfile:
        spamreader = csv.reader(csvfile, delimiter='|', quotechar='"')
        header = next(spamreader)
        for row in spamreader:
            item = dict(zip(header, row))
            for key in header:
                if item[key] == '':
                    del item[key]
            parent = 'parent' in item and Taxon.objects.filter(epithet=item['parent']).first() or None
            if parent is None:
                continue
            rank_name = {'1': 'familia',
                         '2': 'subfamilia',
                         '3': 'tribus',
                         '4': 'subtribus'}.get(item['rank'])
            if rank_name is None:
                continue
            accepted = 'accepted' in item and Taxon.objects.filter(epithet=item['accepted']).first() or None
            rank = Rank.objects.get(name=rank_name)
            try:
                obj = Taxon.objects.get(epithet=item['epithet'], rank=rank)
            except:
                last_id += 1
                obj = Taxon.objects.create(id=last_id, epithet=item['epithet'], rank=rank)
            obj.parent = parent
            obj.accepted = accepted
            obj.authorship = item.get('authorship', '')
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0009_auto_20190507_0147'),
    ]

    operations = [
        migrations.RunPython(import_families),
    ]
