# Generated by Django 2.2 on 2019-05-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0012_auto_20190523_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='family',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='taxon',
            name='genus',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
