# Generated by Django 2.2.4 on 2019-08-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0013_auto_20190530_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='epithet_phonetic',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
