# Generated by Django 2.2.4 on 2019-08-26 21:25

from django.db import migrations


def update_phonetic(apps, schema_editor):
    Taxon = apps.get_model('taxonomy', 'Taxon')
    for taxon in Taxon.objects.all():
        taxon.save()

        
class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0014_taxon_epithet_phonetic'),
    ]

    operations = [
        migrations.RunPython(update_phonetic),
    ]
