# Generated by Django 2.2.4 on 2019-08-26 21:25

from django.db import migrations
from taxonomy.utils import make_phonetic


def update_phonetic(apps, schema_editor):
    Taxon = apps.get_model('taxonomy', 'Taxon')
    bulk = []
    threshold = 375
    for taxon in Taxon.objects.all():
        if taxon.epithet_phonetic != make_phonetic(taxon.epithet):
            taxon.epithet_phonetic = make_phonetic(taxon.epithet)
            bulk.append(taxon)
            if len(bulk) > threshold:
                Taxon.bulk_update(bulk, ['epithet_phonetic'])
                bulk = []
    Taxon.bulk_update(bulk, ['epithet_phonetic'])

        
class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0014_taxon_epithet_phonetic'),
    ]

    operations = [
        migrations.RunPython(update_phonetic),
    ]
