# Generated by Django 2.2 on 2019-04-21 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=64, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='collection.Accession')),
            ],
        ),
        migrations.CreateModel(
            name='LocationPlanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_done', models.DateField()),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Accession')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.Location')),
                ('plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='garden.Plant')),
            ],
        ),
    ]
