# Generated by Django 2.2 on 2019-04-22 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_auto_20190421_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='garden.Location'),
            preserve_default=False,
        ),
    ]
