# Generated by Django 2.2 on 2019-04-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_plant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
